### ISSUE TITLE
Solve persistence

### ISSUE THREAD

**Issue by rafaelnferreira** [rafaelnferreira/katsu-script-manager#4]
We want to have a flexible and non-bureaucratic solution where we will be able to store parametrization.

Check a noSQL solution like MongoDb, Cassandra, Couchbase etc

**Comment by nathanogunleye** [comment]
I've created a ERD diagram. Please have a look:

![database_erd](https://user-images.githubusercontent.com/9629534/74027670-7da85400-49a0-11ea-9d74-98edc48f7726.png)

**Comment by rafaelnferreira** [comment]
My suggestion: Move the attribute 'active' into Job object itself and remove the entity JobStatus.
Instead of JobStatus, create one called JobExecution:
JobId
ExecutionTime
Output (you can store the actual log here or point to a file).
exitCode

**Comment by nathanogunleye** [comment]
> My suggestion: Move the attribute 'active' into Job object itself and remove the entity JobStatus.
> Instead of JobStatus, create one called JobExecution:
> JobId
> ExecutionTime
> Output (you can store the actual log here or point to a file).
> exitCode

I've updated the diagram:

![database_erd](https://user-images.githubusercontent.com/9629534/74036202-b3a30380-49b3-11ea-9e30-514aa759f61b.png)

**Comment by rafaelnferreira** [comment]
One detail just missing the 'ExecutionTime' on JobExecution
After that go ahead and build :)

**Comment by nathanogunleye** [comment]
> One detail just missing the 'ExecutionTime' on JobExecution
> After that go ahead and build :)

Thanks. Updated.

![database_erd](https://user-images.githubusercontent.com/9629534/74036723-b520fb80-49b4-11ea-8020-ae79a492c489.png)
